### ISSUE TITLE
 R-openblas-in-windows

### ISSUE THREAD

**Issue by hermannheringer** [david-cortes/R-openblas-in-windows#1]
Dude, thanks so much for this!

I tried to get it to work with current iterations of Numpy for Windows and it didn't work. The last version of openblas lib that works using the actual R_4.3.0 on Windows as a base is numpy-1.21.6-cp37-cp37m-win_amd64.whl

I was using for years Intel oneMKL for BLAS/LAPACK libraries but I started having problems with some libraries in R, with your solution, now everything is ok!

**Comment by david-cortes** [comment]
Thanks for the information. I've updated the tutorial now to point at the github page of openblas.

**Comment by MAC-GH** [comment]
> Dude, thanks so much for this!
> 
> I tried to get it to work with current iterations of Numpy for Windows and it didn't work. The last version of openblas lib that works using the actual R_4.3.0 on Windows as a base is numpy-1.21.6-cp37-cp37m-win_amd64.whl
> 
> I was using for years Intel oneMKL for BLAS/LAPACK libraries but I started having problems with some libraries in R, with your solution, now everything is ok!

Hello @hermannheringer,

Are you using the oneMKL libraries from MRO or you are using some newer version available from https://www.intel.com/content/www/us/en/developer/tools/oneapi/onemkl-download.html?operatingsystem=window&distributions=pip ? Could you please share some details if you use some version (pip, NuGet, etc.) from the Intel's website ?

Thanks and regards
